class Utils:
    TAGS = {'[123]': '<b>', '[456]': '</b>'}
    STANDARDIZED_PAGE_HEIGHT = 11.69
    STANDARDIZED_PAGE_WIDTH = 8.27
    STANDARDIZED_TOP_MARGIN = 1.48
    STANDARDIZED_BOTTOM_MARGIN = 1.38
    STANDARDIZED_LEFT_MARGIN = 1.38
    STANDARDIZED_RIGHT_MARGIN = 1.38
    STANDARDIZED_FOOTER_DISTANCE = 1
    USABLE_PAGE_HEIGHT = (STANDARDIZED_PAGE_HEIGHT - STANDARDIZED_TOP_MARGIN - STANDARDIZED_BOTTOM_MARGIN)
    USABLE_PAGE_WIDTH = (STANDARDIZED_PAGE_WIDTH - STANDARDIZED_LEFT_MARGIN - STANDARDIZED_RIGHT_MARGIN)
    TYPE_PARAGRAPH = "paragraph"
    TYPE_TABLE = "table"